/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service_impl.QLLoaiKhachHangService;
import viewmodels.LoaiKhachHangViewModel;

/**
 *
 * @author khact
 */
public class ViewLoaiKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form ViewLoaiKhachHang
     */
    private DefaultTableModel tableModel;
    private String[] column = {"ID", "Mã Khách Hàng", "Loại Khách Hàng"};
    private QLLoaiKhachHangService qLLoaiKhachHangService;

    public ViewLoaiKhachHang() {
        initComponents();
//        getContentPane().setBackground(Color.gray); // d?i background trong Jrame
        this.txtIDLoaiKH.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Loại Khách Hàng");
        qLLoaiKhachHangService = new QLLoaiKhachHangService();
        loadData();
    }

    public void loadData() {
        tableModel = new DefaultTableModel(column, 0);
        tblBangLoaiKH.setModel(tableModel);
        List<LoaiKhachHangViewModel> list = qLLoaiKhachHangService.getLoaiKhachHangService();
        tableModel.setRowCount(0);
        for (LoaiKhachHangViewModel a : list) {
            tableModel.addRow(new Object[]{a.getId(), a.getMa(), a.getLoai()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDLoaiKH = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        txtLoaiKH = new javax.swing.JTextField();
        tbnAdd = new javax.swing.JButton();
        tbnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangLoaiKH = new javax.swing.JTable();
        tbnClear = new javax.swing.JButton();
        txtThongBaoLoiID = new javax.swing.JLabel();
        txtThongBaoLoiMa = new javax.swing.JLabel();
        txtThongBaoLoiLoai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ID:");

        jLabel2.setText("Mã:");

        jLabel3.setText("Loại KH:");

        tbnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        tbnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnAddActionPerformed(evt);
            }
        });

        tbnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        tbnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnUpdateActionPerformed(evt);
            }
        });

        tblBangLoaiKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Mã KH", "Loại Khách Hàng"
            }
        ));
        tblBangLoaiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangLoaiKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangLoaiKH);

        tbnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Seanau-Email-Clear.32.png"))); // NOI18N
        tbnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnClearActionPerformed(evt);
            }
        });

        txtThongBaoLoiID.setForeground(new java.awt.Color(255, 0, 51));

        txtThongBaoLoiMa.setForeground(new java.awt.Color(255, 0, 51));

        txtThongBaoLoiLoai.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThongBaoLoiID, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThongBaoLoiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThongBaoLoiLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(tbnAdd)
                .addGap(47, 47, 47)
                .addComponent(tbnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(tbnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIDLoaiKH, txtLoaiKH, txtMaKH});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tbnAdd, tbnUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThongBaoLoiID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThongBaoLoiMa, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(txtThongBaoLoiLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnAdd)
                    .addComponent(tbnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tbnAdd, tbnUpdate});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBangLoaiKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangLoaiKHMouseClicked
        int index = tblBangLoaiKH.getSelectedRow();
        txtIDLoaiKH.setText(tblBangLoaiKH.getValueAt(index, 0).toString());
        txtMaKH.setText(tblBangLoaiKH.getValueAt(index, 1).toString());
        txtLoaiKH.setText(tblBangLoaiKH.getValueAt(index, 2).toString());
    }//GEN-LAST:event_tblBangLoaiKHMouseClicked

    private void tbnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnClearActionPerformed
        xoaTrang();
    }//GEN-LAST:event_tbnClearActionPerformed

    private void tbnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnAddActionPerformed
        StringBuilder builder = new StringBuilder();
        if (txtMaKH.getText().trim().equals("")) {
            builder.append("Mã Loại KH, ");
        }
        if (txtLoaiKH.getText().trim().equals("")) {
            builder.append("Loại KH, ");
        }
        if (builder.length() > 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập " + builder.replace(builder.length() - 2, builder.length(), "."));
            return;
        }
        List<LoaiKhachHangViewModel> list = qLLoaiKhachHangService.getLoaiKhachHangService();
        for (LoaiKhachHangViewModel a : list) {
            if (txtIDLoaiKH.getText().equals(a.getId())) {
                txtThongBaoLoiID.setText("Vui Lòng Clear roi nhap!");
                txtIDLoaiKH.setText("");
                return;
            } else {
                txtThongBaoLoiID.setText("");
            }
            if (txtMaKH.getText().equals(a.getMa())) {
                txtThongBaoLoiMa.setText("Mã Loại Đã Tồn Tại Vui Lòng Nhập Lại");
                return;
            } else {
                txtThongBaoLoiMa.setText("");
            }
        }
        int a;
        try {
            a = Integer.parseInt(txtLoaiKH.getText());
        } catch (NumberFormatException e) {
            txtThongBaoLoiLoai.setText("Vui Lòng Bạn Nhập Loại Là Số!");
            return;
        } finally {
            txtThongBaoLoiLoai.setText("");
        }
        LoaiKhachHangViewModel kh = new LoaiKhachHangViewModel();
        kh.setMa(txtMaKH.getText().trim().toUpperCase());
        kh.setLoai(a);
        Integer ketQua = qLLoaiKhachHangService.addLoaiKhachHang(kh);
        if (ketQua != null) {
            JOptionPane.showMessageDialog(this, "Them Thanh Cong!");
        } else {
            JOptionPane.showMessageDialog(this, "Them Khong Thanh Cong!");
        }
        loadData();
    }//GEN-LAST:event_tbnAddActionPerformed

    private void tbnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnUpdateActionPerformed
        StringBuilder builder = new StringBuilder();
        if (txtIDLoaiKH.getText().equals("") && txtMaKH.getText().trim().equals("") && txtLoaiKH.getText().trim().equals("")) {
            txtThongBaoLoiID.setText("Vui Lòng Chon ID!");
            txtThongBaoLoiMa.setText("Vui Long Nhap Ma");
            txtThongBaoLoiLoai.setText("Vui Lòng Bạn Nhập Loại!");
            return;
        } else {
            txtThongBaoLoiID.setText("");
            txtThongBaoLoiMa.setText("");
            txtThongBaoLoiLoai.setText("");
        }
        List<LoaiKhachHangViewModel> list = qLLoaiKhachHangService.getLoaiKhachHangService();
        for (LoaiKhachHangViewModel a : list) {
            if (txtMaKH.getText().equals(a.getMa())) {
                txtThongBaoLoiMa.setText("Mã Loại Đã Tồn Tại Vui Lòng Nhập Lại");
                return;
            } else {
                txtThongBaoLoiMa.setText("");
            }
        }
        int a;
        try {
            a = Integer.parseInt(txtLoaiKH.getText());
        } catch (NumberFormatException e) {
            txtThongBaoLoiLoai.setText("Vui Lòng Bạn Nhập Loại Là Số!");
            return;
        } finally {
            txtThongBaoLoiLoai.setText("");
        }
        LoaiKhachHangViewModel kh = new LoaiKhachHangViewModel();
        kh.setId(txtIDLoaiKH.getText());
        kh.setMa(txtMaKH.getText().trim().toUpperCase());
        kh.setLoai(a);
        Integer ketQua = qLLoaiKhachHangService.updateLoaiKhachHang(kh);
        if (ketQua != null) {
            JOptionPane.showMessageDialog(this, "Sua Thanh Cong!");
        } else {
            JOptionPane.showMessageDialog(this, "Sua Khong Thanh Cong!");
        }
        loadData();
    }//GEN-LAST:event_tbnUpdateActionPerformed

    private void xoaTrang() {
        txtIDLoaiKH.setText("");
        txtMaKH.setText("");
        txtLoaiKH.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLoaiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLoaiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLoaiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLoaiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLoaiKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangLoaiKH;
    private javax.swing.JButton tbnAdd;
    private javax.swing.JButton tbnClear;
    private javax.swing.JButton tbnUpdate;
    private javax.swing.JTextField txtIDLoaiKH;
    private javax.swing.JTextField txtLoaiKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JLabel txtThongBaoLoiID;
    private javax.swing.JLabel txtThongBaoLoiLoai;
    private javax.swing.JLabel txtThongBaoLoiMa;
    // End of variables declaration//GEN-END:variables
}
